### ISSUE TITLE
Slow/Not Working in Firefox

### ISSUE THREAD

**Issue by apopiak** [Colm3na/kusama-validator-resource-center#46]
It seems https://colm3na.github.io/kusama-validator-resource-center/ is not working or very slow in Firefox. (Stuck in the loading animation. Chromium loads fine.)

Firefox Developer Edition 83.0b4 (64-Bit), Ubuntu 20.04.1 LTS

**Comment by mariopino** [comment]
Thanks @apopiak, checking!

**Comment by mariopino** [comment]
Seems slower in Firefox, but worked for me:

Firefox 82.0.2:

data collection time: 131.244s
data processing time: 23.415s
total time: 154.659s

Chome 86.0.4240.111:

data collection time: 113.949s
data processing time: 16.112s
total time: 130.061s

Need to figure out why.

**Comment by apopiak** [comment]
Just did another test and now it loaded :shrug:
