### ISSUE TITLE
Include "Participating in Governance" as any sub or super identity

### ISSUE THREAD

**Issue by wpank** [Colm3na/kusama-validator-resource-center#93]
![factors](https://user-images.githubusercontent.com/9498646/101018942-83dd7180-356c-11eb-91c7-cda1baf623dc.png)

Jaco is indeed participating in governance, but not with this sub-identity. "Participating in Governance" should be counted as any of the sub or super identities.

**Comment by mariopino** [comment]
Thanks @wpank, it will be addresed shortly
